### ISSUE TITLE
Login URI on 9991 not 8080

### ISSUE THREAD

**Issue by OlivierMary** [monkey-codes/spring-boot-authentication#3]
Hi, first thanks for all this good job.

I don't understand something with your zuul config:

```yml
zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9991/auth/
      sensitive-headers:
    resource:
      path: /api/**
      url: http://localhost:9992/
      sensitive-headers:
```
Why when I go on `http://localhost:8080/wep-app` I'm redirect to `http://localhost:9991/auth/login` and not `http://localhost:8080/wep-app/auth/login` why ? After login all call to `/api/` call `http://localhost:8080/web-app/api/1` so zuul config ok after login.

I can go on `http://localhost:8080/web-app/auth/login` directly but it's not the goal.

Any idea?
